name: ssrf server

on:

  push:
    branches:
      - master
      - develop
    paths:
      - 'docker/ssrf-server/resources/server/**'
      - '.github/workflows/ssrf-server.yml'


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: ${{ github.event.repository.name }}
      uses: actions/checkout@v4

    - name: Set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 8
        cache: maven
        cache-dependency-path: docker/ssrf-server/resources/server/pom.xml

    - name: Build with Maven
      run: cd docker/ssrf-server/resources/server && mvn -B package --file pom.xml

    - name: Archive generated JAR file
      uses: actions/upload-artifact@v4
      with:
        name: ssrf-server
        path: docker/ssrf-server/resources/server/target/*.jar
